[package]
name = "qcm_autologin_service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json"] }
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
log = "0.4"
env_logger = "0.11"
headless_chrome = "1.0"
clap = { version = "4", features = ["derive"] }

[target.'cfg(windows)'.dependencies]
windows-service = "0.6"
winapi = { version = "0.3.9", features = [
  "wtsapi32",
  "winbase",
  "winuser",
  "processthreadsapi",
  "securitybaseapi",
  "handleapi",
  "userenv",
  "winnt"
] }
